### ISSUE TITLE
Snackbar not rendering properly

### ISSUE THREAD

**Issue by Modjular** [the-rango/AntAlmanac#105]
### Issue
![Screen Shot 2020-12-01 at 4 51 21 PM](https://user-images.githubusercontent.com/8238329/100820070-4d83e300-3402-11eb-819b-f085bc5f2fab.png)

### Potential Causes?
After some digging, I have some guesses

- Something to do with `position: relative` in `.MuiButtonBase-root` because disabling it in the inspector "fixes" it but causes problems with the buttons themselves.
- Something to do with the z-index being manually set?
- [This article](https://coder-coder.com/z-index-isnt-working/) mentions something about absolute vs relative, and which gets the priority during render

**Comment by ChaseC99** [comment]
Thanks for reporting this! 
We have addressed this bug in the new rewrite of AntAlmanac.
