### ISSUE TITLE
Light colored events

### ISSUE THREAD

**Issue by the-rango** [the-rango/AntAlmanac#52]
![If you change the color of the event to white](https://cdn.discordapp.com/attachments/559525861821251595/574829109004337152/Screen_Shot_2019-05-05_at_10.24.14_PM.png)

When changing color of events to light colors, font color should change accordingly for better visibility. Also add border in case of white.

**Comment by ChaseC99** [comment]
Addressed this bug in the new rewrite of AntAlmanac.
