### ISSUE TITLE
Replace all use of `var` with `let` (or `const` when possible)

### ISSUE THREAD

**Issue by wytesk133** [the-rango/AntAlmanac#57]
`var` leads to [hoisting](https://medium.com/javascript-in-plain-english/https-medium-com-javascript-in-plain-english-what-is-hoisting-in-javascript-a63c1b2267a1) and and should be avoided in modern ES6 code base.

**Comment by the-rango** [comment]
Thanks!
I think we might still have a few ES6 issues, and we'll revise all code before and during summer!
