### ISSUE TITLE
MobileCalender.js: Undefined variable 'getDay'

### ISSUE THREAD

**Issue by PepziC0les** [the-rango/AntAlmanac#59]
When accessing older schedules on both mobile and desktop (specifically when the window is minimized for desktop), error occurs with getDay variable, declaring it as undefined. Newer schedules work perfectly fine.

**Comment by the-rango** [comment]
Are you taking 6D this quarter? Or next?

**Comment by the-rango** [comment]
The problem was online/tba courses. You can add them now, but they do not show up on the calendar. Thus they don't have a "start" object and you cannot call 'getDay' on them. 
Thanks! And we really appreciate all the users who submitted a bug report about this!!
