### ISSUE TITLE
iphone Mobile || Advanced search wonky UI

### ISSUE THREAD

**Issue by giannatn** [the-rango/AntAlmanac#61]
Bug Reproduction:
-go to mobile
-open drop down for advanced search

Fields overlap each other and the search button
https://media.discordapp.net/attachments/558501572456480780/582630921749004289/image0.png?width=373&height=663

**Comment by the-rango** [comment]
We've removed some of the text at the bottom, and moved things around on the search form for mobile. 
How does it look now?

**Comment by giannatn** [comment]
The course start after and end before parts are cut off.

**Comment by the-rango** [comment]
@devsdevsdevs do people actually use the start-after and end-before?

**Comment by the-rango** [comment]
Apparently, start-after and end-before look like cut-off but is actually clickable on mobile
iOS: https://cdn.discordapp.com/attachments/559525861821251595/603608654259814531/image0.png
Android:
https://cdn.discordapp.com/attachments/544250967286087692/604178124082642944/Screenshot_20190725-220756.png
Also added larger selector for depts on mobile:
https://cdn.discordapp.com/attachments/559525861821251595/604365881178325003/unknown.png
