### ISSUE TITLE
Preview color circle appears as transparent instead of the correct color, sometimes

### ISSUE THREAD

**Issue by fatimazali** [the-rango/AntAlmanac#67]
This occurs both on the calendar and in the added classes list: 
<img width="472" alt="Screen Shot 2019-06-17 at 2 46 42 PM" src="https://user-images.githubusercontent.com/43034257/59639125-1e46bc80-910f-11e9-9c8f-10873fd4b19b.png">
 <img width="788" alt="Screen Shot 2019-06-17 at 2 50 21 PM" src="https://user-images.githubusercontent.com/43034257/59639173-46ceb680-910f-11e9-9ee0-659cbff5ee00.png">

I'm still able to click the transparent circle to adjust the color of the class.

**Comment by the-rango** [comment]
Yeah the color picker does that when it encounters an error, which is a dumb way of failing silently. I looked into it briefly, not exactly sure why it's doing that. 
Thanks for making the issue!

**Comment by the-rango** [comment]
As a temporary hotfix, I put in an if-block to catch undefined colors.
@Indigo-N-I If the rewrite no longer requires unique colors, this shouldnt be a issue in that branch.

**Comment by ChaseC99** [comment]
Thanks for reporting this!
We have addressed this bug in the new rewrite of AntAlmanac.
