### ISSUE TITLE
Laggy When Hover Over Course Code

### ISSUE THREAD

**Issue by tjhu** [the-rango/AntAlmanac#68]
It's slow to scroll when hover the mouse over the course code on the search result pane. It's normal if I place the mouse somewhere else.

![out-1](https://user-images.githubusercontent.com/18585305/59642509-1dffee80-911a-11e9-980a-7eae30cd2c8d.gif)

**Comment by ChaseC99** [comment]
Thanks for reporting! This should be fixed in the new rewrite. If the issue still persists for you on https://antalmanac.com/ please re-open this issue.
