### ISSUE TITLE
Missing ./f18.json file?

### ISSUE THREAD

**Issue by poppy567** [the-rango/AntAlmanac#93]
Seems like the f18.json file doesn't exist in the dir: src/components/AlmanacGraph.

**Comment by devsdevsdevs** [comment]
That file contains grade distribution info. For now, we're not putting this file up on the VCS. You can safely comment out that line and all references to it and disable that feature so you can set up the environment.

**Comment by the-rango** [comment]
If you really wanna play around with it, email us, and we'll send it to you
antalmanac@gmail.com

**Comment by ChaseC99** [comment]
Closing this issue since it is no longer relevant for the rewrite.
